#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 31 12:57:02 2016
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one 

more letter at a random position.

Find the letter that was added in t.
@author: carlosjarguello
"""

def findTheDifference(s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    from collections import Counter
    s_dict = Counter(list(s))
    t_dict = Counter(list(t))
    for key, value in t_dict.items():
        if s_dict.get(key,0) == 0 or s_dict[key] != value:
            return key
    return
    
print findTheDifference('abcd','abacd')